version: '3'
services:
  lemmingpants-frontend:
    image: lemmingpants-frontend:latest
    container_name: lemmingpants-frontend
    ports:
      - "8000:80"
    depends_on:
      - db
      - ws
      - lemmingpants

  lemmingpants:
    image: lemmingpants-backend:latest
    container_name: lemmingpants
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/init.sql
      - ./sql:/sql
    environment:
      POSTGRES_USER: lemmingpants
      POSTGRES_PASSWORD: lemmingpants
      POSTGRES_DB: lemmingpants

  ws:
    image: diogob/postgres-websockets
    environment:
      PGWS_DB_URI: postgres://lemmingpants:lemmingpants@db/lemmingpants
      PGWS_JWT_SECRET: "feBU1ykZ4icKs2nKam9l8CD84qhgeOl6QQakrUJBiRTUu4dKTLVoH8o"
    ports:
        - "3001:3000"
    depends_on:
      - lemmingpants
      - db
