version: "3"
services:
  lemmingpants-frontend:
    image: lemmingpants-frontend:latest
    container_name: lemmingpants-frontend
    volumes:
      - static:/srv/static/

  lemmingpants-backend:
    image: lemmingpants-backend:latest
    container_name: lemmingpants-backend
    restart: always
    environment:
      PGWS_DB_URI: postgres://lemmingpants:lemmingpants@db/lemmingpants
      PGWS_JWT_SECRET: "feBU1ykZ4icKs2nKam9l8CD84qhgeOl6QQakrUJBiRTUu4dKTLVoH8o"
    ports:
      - "5432:5432"
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./init.sql:/init.sql
      - ./pg_tests:/pg_tests
      - ./sql:/sql
