- name: Provision Python
  hosts: all
  gather_facts: no
  tasks:
    - name: Bootstrap Python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: Create needed directories
  hosts: all
  gather_facts: no
  tasks:
    - name: Create the /setup-directory.
      file: path=/setup state=directory

- name: Install psc-package
  hosts: all
  tasks:
    - name: Download psc-package tarball
      get_url: https://github.com/purescript/psc-package/releases/download/v0.4.2/linux64.tar.gz
      dest: /setup
      checksum: sha1:bdf25acc5b4397bd03fd1da024896c5f33af85ce

# Frontendy stuff
- name: Install Purescript
  hosts: all
  tasks:
    - name: Does purs exist?
      stat: path=/usr/local/bin/purs
      register: purs_binary
    - name: Download Purescript tarball.
      when: purs_binary.stat.exists == False
      get_url:
        url: https://github.com/purescript/purescript/releases/download/v0.12.0/linux64.tar.gz
        dest: /setup
        checksum: sha1:08d4839f2800a6fdb398ec45b7182eada112ea89
    - name: Unpack Purescript compiler
      when: purs_binary.stat.exists == False
      unarchive:
        src: /setup/linux64.tar.gz
        dest: /setup
        remote_src: yes
    - name: Copy compiler executable to the right place
      when: purs_binary.stat.exists == False
      copy:
        src: /setup/purescript/purs
        dest: /usr/local/bin
        mode: 0755
        remote_src: yes

- name: Install Google Closure Compiler
  https://dl.google.com/closure-compiler/compiler-latest.zip
